"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { LogOut, Save, ShieldCheck, Settings2 } from "lucide-react";
import { defaultContent, SiteContent } from "@/lib/content";
import { getSupabaseBrowser } from "@/lib/supabase-browser";

export default function AdminPage() {
  const supabase = getSupabaseBrowser();
  const [user, setUser] = useState<string | null>(null);
  const [content, setContent] = useState<SiteContent>(defaultContent);
  const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!supabase) return; supabase.auth.getUser().then(({ data }) => setUser(data.user?.email ?? null)); }, [supabase]);
  async function login(e: FormEvent) { e.preventDefault(); if (!supabase) return; setMessage("Memproses login..."); const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) setMessage(error.message); else { setUser(email); setMessage("Login berhasil."); await loadContent(); } }
  async function loadContent() { if (!supabase) return; const { data } = await supabase.from("site_content").select("payload").eq("slug", "main").maybeSingle(); if (data?.payload) setContent({ ...defaultContent, ...data.payload }); }
  async function save() { if (!supabase) return; setSaving(true); const { error } = await supabase.from("site_content").upsert({ slug: "main", payload: content, updated_at: new Date().toISOString() }); setSaving(false); setMessage(error ? error.message : "Konten berhasil disimpan."); }
  function setField(section: keyof SiteContent, field: string, value: string) { setContent((old) => ({ ...old, [section]: { ...(old[section] as object), [field]: value } })); }
  if (!supabase) return <AdminShell><SetupCard/></AdminShell>;
  if (!user) return <AdminShell><form className="admin-login" onSubmit={login}><div className="admin-badge"><ShieldCheck size={22}/></div><span className="section-kicker">Area pengelola</span><h1>Masuk ke admin panel</h1><p>Kelola isi website Yayasan Pondok Pesantren Al Huda.</p><label>Email<input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="admin@contoh.com"/></label><label>Password<input type="password" required value={password} onChange={(e) => setPassword(e.target.value)} placeholder="••••••••"/></label><button className="button button-primary full" type="submit">Masuk</button>{message && <div className="admin-message">{message}</div>}</form></AdminShell>;
  return <AdminShell><div className="admin-top"><div><span className="section-kicker">Dashboard</span><h1>Kelola konten website</h1><p>Login sebagai {user}. Perubahan akan tampil pada website setelah disimpan.</p></div><div className="button-row"><Link className="button button-outline" href="/">Lihat website</Link><button className="button button-primary" onClick={save} disabled={saving}><Save size={17}/>{saving ? "Menyimpan..." : "Simpan perubahan"}</button><button className="icon-button" aria-label="Keluar" onClick={() => supabase.auth.signOut().then(() => setUser(null))}><LogOut size={18}/></button></div></div>{message && <div className="admin-message success">{message}</div>}<div className="admin-grid"><section className="admin-panel"><div className="panel-heading"><Settings2 size={19}/><h2>Hero dan identitas</h2></div><Field label="Nama yayasan" value={content.brand.name} onChange={(v) => setField("brand", "name", v)}/><Field label="Tagline" value={content.brand.tagline} onChange={(v) => setField("brand", "tagline", v)}/><Field label="Judul hero" value={content.hero.title} onChange={(v) => setField("hero", "title", v)}/><TextArea label="Deskripsi hero" value={content.hero.description} onChange={(v) => setField("hero", "description", v)}/></section><section className="admin-panel"><div className="panel-heading"><Settings2 size={19}/><h2>Kontak dan tautan</h2></div><TextArea label="Alamat" value={content.contact.address} onChange={(v) => setField("contact", "address", v)}/><Field label="WhatsApp URL" value={content.contact.whatsappUrl} onChange={(v) => setField("contact", "whatsappUrl", v)}/><Field label="Google Maps URL" value={content.contact.mapUrl} onChange={(v) => setField("contact", "mapUrl", v)}/><Field label="Link PPDB / Google Form" value={content.ppdbUrl} onChange={(v) => setContent((old) => ({ ...old, ppdbUrl: v }))}/><Field label="Link donasi" value={content.donation.url} onChange={(v) => setField("donation", "url", v)}/></section><section className="admin-panel admin-panel-wide"><div className="panel-heading"><Settings2 size={19}/><h2>Data unit, program, dan berita</h2></div><p className="panel-help">Untuk tahap awal, data berbentuk JSON agar seluruh isi dapat diedit. Struktur ini akan dikembangkan menjadi editor visual pada tahap berikutnya.</p><textarea className="json-editor" value={JSON.stringify({ units: content.units, programs: content.programs, news: content.news }, null, 2)} onChange={(e) => { try { const next = JSON.parse(e.target.value); setContent((old) => ({ ...old, ...next })); setMessage(""); } catch { setMessage("Format JSON belum valid."); } }} /></section></div></AdminShell>;
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}) { return <label className="admin-field">{label}<input value={value} onChange={(e) => onChange(e.target.value)}/></label> }
function TextArea({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}) { return <label className="admin-field">{label}<textarea value={value} onChange={(e) => onChange(e.target.value)} rows={4}/></label> }
function AdminShell({children}:{children:React.ReactNode}) { return <main className="admin-page"><div className="container">{children}</div></main> }
function SetupCard() { return <div className="setup-card"><div className="admin-badge"><ShieldCheck size={22}/></div><span className="section-kicker">Admin panel belum terhubung</span><h1>Tambahkan Supabase untuk mulai mengelola konten</h1><p>Website sudah memiliki dashboard admin. Ikuti panduan di README untuk membuat database, akun admin, dan menambahkan environment variables di Vercel.</p><Link className="button button-primary" href="https://supabase.com" target="_blank">Buka Supabase</Link></div> }
