import Link from "next/link";
import { ArrowRight, Check, Sparkles } from "lucide-react";
import { getSiteContent } from "@/lib/content-server";

export default async function HomePage() {
  const c = await getSiteContent();
  return <main>
    <section className="hero"><div className="hero-glow"/><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot"/>{c.hero.eyebrow}</div><h1>{c.hero.title}</h1><p className="hero-description">{c.hero.description}</p><div className="button-row"><Link className="button button-primary" href={c.hero.primaryCtaHref}>{c.hero.primaryCtaLabel}<ArrowRight size={17}/></Link><Link className="button button-ghost" href={c.hero.secondaryCtaHref}>{c.hero.secondaryCtaLabel}</Link></div></div><div className="hero-visual"><div className="arch-card"><div className={c.hero.imageUrl ? "arch-sky has-photo" : "arch-sky"} style={c.hero.imageUrl ? { backgroundImage: `url(${c.hero.imageUrl})` } : undefined}>{!c.hero.imageUrl && <><div className="sun"/><div className="mosque-line"><span/><span/><span/><span/><span/></div></>}</div><div className="arch-caption"><span>Al Huda</span><strong>Ruang tumbuh bagi generasi</strong><small>Pamijahan · Cirebon</small></div></div><div className="floating-note"><Sparkles size={16}/><span>Berilmu<br/><b>Berakhlak</b></span></div></div></div></section>
    <section className="stats-strip"><div className="container stats-grid">{c.stats.map((item) => <div className="stat" key={item.label}><strong>{item.value}</strong><span>{item.label}</span></div>)}</div></section>
    <section className="section"><div className="container split-grid"><div><span className="section-kicker">Tentang yayasan</span><h2>{c.about.title}</h2><p className="lead">{c.about.body}</p><Link className="text-link" href="/profil">Mengenal Al Huda lebih dekat <ArrowRight size={16}/></Link></div><div className="value-card"><div className="value-card-top"><span className="ornament">✦</span><span>Nilai yang kami jaga</span></div>{c.about.values.map((value, i) => <div className="value-item" key={`${value}-${i}`}><span>0{i + 1}</span><strong>{value}</strong><Check size={17}/></div>)}</div></div></section>
    <section className="section section-soft"><div className="container"><div className="section-heading"><div><span className="section-kicker">Unit pendidikan</span><h2>Tempat belajar dan bertumbuh</h2></div><Link className="text-link" href="/unit-pendidikan">Lihat semua <ArrowRight size={16}/></Link></div><div className="unit-grid">{c.units.map((unit, i) => <article className="unit-card" key={`${unit.name}-${i}`}><div className={i === 0 ? "card-number gold" : "card-number"}>0{i + 1}</div><span className="card-label">{unit.level}</span><h3>{unit.name}</h3><p>{unit.description}</p><div className="card-footer"><span>{unit.accreditation}</span><ArrowUpRightIcon/></div></article>)}</div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><div><span className="section-kicker">Ikhtiar kami</span><h2>Program yang membentuk karakter</h2></div><Link className="text-link" href="/program">Lihat program <ArrowRight size={16}/></Link></div><div className="program-grid">{c.programs.map((program, i) => <article className="program-card" key={`${program.title}-${i}`}><span className="program-icon">{program.icon}</span><h3>{program.title}</h3><p>{program.description}</p><ArrowRight className="program-arrow" size={18}/></article>)}</div></div></section>
    <section className="section news-section"><div className="container"><div className="section-heading"><div><span className="section-kicker">Kabar Al Huda</span><h2>Informasi dan kegiatan terbaru</h2></div><Link className="text-link" href="/berita">Buka berita <ArrowRight size={16}/></Link></div><div className="news-grid">{c.news.map((item, i) => <article className="news-card" key={`${item.title}-${i}`}><div className={item.imageUrl ? "news-image has-photo" : "news-image"} style={item.imageUrl ? { backgroundImage: `url(${item.imageUrl})` } : undefined}><span>{item.category}</span>{!item.imageUrl && <div className="news-pattern"/>}</div><div className="news-body"><span className="news-date">{item.date}</span><h3>{item.title}</h3><p>{item.excerpt}</p><Link href="/berita" className="text-link">Baca selengkapnya <ArrowRight size={15}/></Link></div></article>)}</div></div></section>
    <section className="cta-section"><div className="container cta-inner"><div><span className="section-kicker light">Mari terhubung</span><h2>Membangun masa depan melalui pendidikan.</h2><p>Untuk informasi pendaftaran, kerja sama, atau dukungan program, silakan hubungi pengelola yayasan.</p></div><Link className="button button-light" href="/kontak">Hubungi kami <ArrowRight size={17}/></Link></div></section>
  </main>;
}
function ArrowUpRightIcon() { return <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M7 17 17 7M7 7h10v10"/></svg>; }
